SELECT 
    id, id_logradouro, 
    nome_logradouro, 
    numero_porta, 
    id_projeto_loteamento, 
    id_processo, 
    data_abertura_processo, 
    data_emissao_processo, 
    quantidade_processos,
    id_licenca, 
    classe_licenca, 
    tipo_licenca, 
    descricao_licenca,
    data_inicio_validade, 
    data_vencimento_validade,
    quantidade_licencas, 
    id_documento_arrecadacao, 
    valor_documento_arrecadacao,
    nome_orgao, nome_requerente, 
    nome_responsavel_projeto, 
    nome_responsavel_obra,
    quantidade_edificacoes, 
    tipo_edificacao, 
    afastamento, 
    tipo_uso, 
    tipo_atividade, 
    legislacao,
    area_total_coberta, 
    area_edificada, 
    area_acrescida, 
    area_reduzida, 
    area_util, 
    quantidade_unidades_total, 
    total_pavimentos,
    geometry 
FROM `rj-seop.urbanismo_geosislic_licenciamento.licencas`
