SELECT 
    id, 
    id_logradouro as id_logrado, 
    nome_logradouro as logradouro, 
    numero_porta as np, 
    id_projeto_loteamento as id_lote, 
    id_processo as id_process, 
    data_abertura_processo as abre_proce, 
    data_emissao_processo as emite_proc, 
    quantidade_processos as n_processo,
    id_licenca, 
    classe_licenca as classe_lic, 
    tipo_licenca as tipo_lic, 
    descricao_licenca as des_lic,
    data_inicio_validade as inicio_lic, 
    data_vencimento_validade as vence_lic,
    quantidade_licencas as n_licenca, 
    id_documento_arrecadacao as id_arrecad, 
    valor_documento_arrecadacao as valor_arre,
    nome_orgao, 
    nome_requerente as requerente, 
    nome_responsavel_projeto as resp_proj, 
    nome_responsavel_obra as resp_obra,
    quantidade_edificacoes as n_edificac, 
    tipo_edificacao as tipo_edifi, 
    afastamento as afastament, 
    tipo_uso, 
    tipo_atividade as tipo_ativ, 
    legislacao,
    area_total_coberta as area_cobert, 
    area_edificada as area_edifi, 
    area_acrescida as area_acres, 
    area_reduzida  as area_reduz, 
    area_util, 
    quantidade_unidades_total as unidades, 
    total_pavimentos as pavimentos,
    geometry 
FROM `rj-seop.urbanismo_geosislic_licenciamento.licencas`
