
SELECT 
    SAFE_CAST(longitude AS STRING) longitude,
    SAFE_CAST(latitude AS STRING) latitude,
    SAFE_CAST(x AS STRING) x,
    SAFE_CAST(y AS STRING) y,
    SAFE_CAST(ap AS STRING) id_area_planejamento,
    SAFE_CAST(rp AS STRING) nome_regiao_planejamento,
    SAFE_CAST(codrp AS STRING) id_regiao_planejamento, 
    SAFE_CAST(ra AS STRING) id_regiao_administrativa, 
    SAFE_CAST(bairro AS STRING) nome_bairro,  
    SAFE_CAST(codbairro AS STRING) id_bairro, 
    SAFE_CAST(logradouro AS STRING) nome_logradouro, 
    SAFE_CAST(clogra AS STRING) id_logradouro, 
    SAFE_CAST(numporta AS STRING) numero_porta,
    SAFE_CAST(pal AS STRING) id_projeto_loteamento,
    SAFE_CAST(num_processo AS STRING) id_processo,
    SAFE_CAST(SAFE.PARSE_DATE('%d/%m/%Y', dtabertura) AS DATE) data_abertura_processo,  
    SAFE_CAST(licenca AS STRING) id_licenca,
    SAFE_CAST(SAFE.PARSE_DATE('%d/%m/%Y', dt_emissao) AS DATE) data_emissao_processo,  
    SAFE_CAST(SAFE.PARSE_DATE('%d/%m/%Y', inicio_validade) AS DATE) data_inicio_validade,  
    SAFE_CAST(prazo AS INT64) prazo_validade_meses,
    SAFE_CAST(SAFE.PARSE_DATE('%d/%m/%Y', vencimento) AS DATE) data_vencimento_validade,  
    SAFE_CAST(num_darm AS STRING) id_documento_arrecadacao,
    SAFE_CAST(valor_darm AS FLOAT64) valor_documento_arrecadacao,
    SAFE_CAST(lic_gratis AS INT64) licenca_gratuita,
    SAFE_CAST(nome_orgao AS STRING) nome_orgao,
    SAFE_CAST(requerente AS STRING) nome_requerente,
    SAFE_CAST(prpa AS STRING) nome_responsavel_projeto,
    SAFE_CAST(preo AS STRING) nome_responsavel_obra,
    SAFE_CAST(classe_licenca AS STRING) classe_licenca,
    SAFE_CAST(tipo_licenca AS STRING) tipo_licenca,
    SAFE_CAST(descricao_licenca AS STRING) descricao_licenca,
    SAFE_CAST(recebe_numeracao AS STRING) recebe_numeracao, # verificar metadado
    SAFE_CAST(cancelado AS STRING) cancelado, # verificar metadado
    SAFE_CAST(conta_edificacao AS STRING) conta_edificacao, # verificar metadado
    SAFE_CAST(tipo_edificacao AS STRING) tipo_edificacao,
    SAFE_CAST(embasamento AS STRING) embasamento, # verificar metadado (booleana)
    SAFE_CAST(implantacao AS STRING) afastamento, 
    SAFE_CAST(uso AS STRING) tipo_uso, 
    SAFE_CAST(atividade AS STRING) tipo_atividade, 
    SAFE_CAST(legislacao AS STRING) legislacao, 
    SAFE_CAST(status AS STRING) status, # verificar metadado 
    SAFE_CAST(qtd_num_proc AS INT64) quantidade_processos, 
    SAFE_CAST(qtd_licencas AS INT64) quantidade_licencas, 
    SAFE_CAST(qtd_edificacoes AS INT64) quantidade_edificacoes, 
    SAFE_CAST(atc AS FLOAT64) area_total_coberta, 
    SAFE_CAST(area_edif AS FLOAT64) area_edificada, 
    SAFE_CAST(area_acresc AS FLOAT64) area_acrescida, 
    SAFE_CAST(area_reduzida AS FLOAT64) area_reduzida, 
    SAFE_CAST(area_util AS FLOAT64) area_util, 
    SAFE_CAST(grupamento AS STRING) grupamento, # var. booleana, conjunto constituído por edificações ou áreas de terreno no mesmo lote, destinadas a unidades autônomas 
    SAFE_CAST(total_etapas AS INT64) total_etapas, # verificar metadado
    SAFE_CAST(total_edif_etapa AS INT64) total_etapas_edificacao, # verificar metadado
    SAFE_CAST(area_unid_total AS FLOAT64) area_unidade_total, # verificar metadado
    SAFE_CAST(area_unid_residencial AS FLOAT64) area_unidade_residencial, 
    SAFE_CAST(area_unid_resid_uni AS FLOAT64) area_unidade_residencial_unifamiliar, 
    SAFE_CAST(area_unid_resid_bi AS FLOAT64) area_unidade_residencial_bifamiliar, 
    SAFE_CAST(area_unid_resid_multi AS FLOAT64) area_unidade_residencial_multifamiliar, 
    SAFE_CAST(area_unid_comercial AS FLOAT64) area_unidade_comercial, 
    SAFE_CAST(area_unid_lojas AS FLOAT64) area_unidade_lojas,
    SAFE_CAST(area_unid_salas AS FLOAT64) area_unidade_salas, 
    SAFE_CAST(area_unid_uso_exclusivo AS FLOAT64) area_unidade_uso_exclusivo, 
    SAFE_CAST(area_unid_industrial AS FLOAT64) area_unidade_industrial, 
    SAFE_CAST(area_unid_outros AS FLOAT64) area_unidade_outros, 
    SAFE_CAST(qtd_unid_total AS INT64) quantidade_unidades_total, 
    SAFE_CAST(qtd_unid_residencial AS INT64) quantidade_unidades_residencial, 
    SAFE_CAST(qtd_unid_resid_uni AS INT64) quantidade_unidades_residencial_unifamiliar, 
    SAFE_CAST(qtd_unid_resid_bi AS INT64) quantidade_unidades_residencial_bifamiliar, 
    SAFE_CAST(qtd_unid_resid_multi AS INT64) quantidade_unidades_residencial_multifamiliar, 
    SAFE_CAST(qtd_unid_nao_residencial AS INT64) quantidade_unidades_nao_residencial, 
    SAFE_CAST(qtd_unid_comercial AS INT64) quantidade_unidades_comercial, 
    SAFE_CAST(qtd_unid_lojas AS INT64) quantidade_unidades_lojas, 
    SAFE_CAST(qtd_unid_salas AS INT64) quantidade_unidades_salas, 
    SAFE_CAST(qtd_unid_uso_exclusivo AS INT64) quantidade_unidades_uso_exclusivo, 
    SAFE_CAST(qtd_unid_industrial AS INT64) quantidade_unidades_industrial, 
    SAFE_CAST(qtd_unid_outros AS INT64) quantidade_unidades_outros, 
    SAFE_CAST(tot_pav AS INT64) total_pavimentos, 
    SAFE_CAST(tot_vagascobertas AS INT64) total_vagas_cobertas, 
    SAFE_CAST(tot_vagasdescobertas AS INT64) total_vagas_descobertas, 
    SAFE_CAST(id AS STRING) id,    
    ST_GEOGPOINT(SAFE_CAST(longitude AS FLOAT64), SAFE_CAST(latitude AS FLOAT64)) AS geometry 
FROM `rj-seop.urbanismo_geosislic_licenciamento_staging.licencas`

